#!/bin/bash
function Proverka_BD {
echo "Проверим установлен ли PostgeSQL на системе"
os_release=$(uname -a)
if [[ *"Ubuntu"* ]]; then
    postgresql -V
    if [[ ]]; then
        sudo apt install postgresql
    fi
elif [[ *"Debian"* ]]; then
    postgresql -V
    if [[ ]]; then
        sudo apt install postgresql
    fi
elif [[ *"Manjaro"* ]]; then
    postgresql -V
    if [[ ]]; then
        sudo pacman -S postgresql
    fi
elif
    echo "ты юзаешь какую то другую систему чел"
}
Proverka_BD

function Proverka_IP {
dig +short shopliz.duckdns.org
dig +short dns_mikrotika
#добавит инфу которая будет добавлять ай пи адрес в бд
}
Proverka_IP

Function Dobavlenie_infy {
#добавить в скрипт для крон проверку днсов
psql -U postgres -p 5432 -h localhost
CREATE DATABASE For_Cron;
CREATE TABLE infa (id BIGSERIAL NOT NULL PRIMARY KEY, Наименование-ДНС_Службы VARCHAR(30) NOT NULL, Имя_ДНС_Службы VARCHAR(50) NOT NULL, ip_address VARCHAR(16);
INSERT INTO infa ('Duck DNS', 'shopliz.duckdns.org', '$ip_address');
INSRRT INTO infa ('Mikrotik DNS', 'dns_mikrotika', '$ip_address');


function Sozdanie_scripta_dlya_Cron {
touch $HOME/script_dlya_cron.sh
chmod+x script_dlya_cron.sh >> sudo crontab -e
}
Sozdanie_scripta_dlya_Cron


function Peredacha_Dannblh_for_file_cron {
#сюда добавить строки которые будут находиться в файле для проверки ай пи адреса в бд и если такого нет, то перезаписывать данные
}
Peredacha_Dannblh_for_file_cron